version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017 # make sure we don't have another mongo container running on same port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin260
    volumes:
      - ./db_data/:/data/db/


