-- Retrieving aggregated information for each department from the EMPLOYEE_INFO table with rounding
SELECT
    DEPTID,
    SUM(EMPSALARY) AS TOTALSALARY,
    COUNT(EMPNAME) AS TOTALEMPLOYEE,
    CAST(AVG(EMPSALARY) AS DECIMAL(10, 2)) AS AVGSALARY,
    MIN(EMPSALARY) AS MINSALARY,
    MAX(EMPSALARY) AS MAXSALARY
FROM
    EMPLOYEE_INFO
GROUP BY
    DEPTID;

