--  MERGE Statement in MS SQL Server 
-- MERGE IS A LOGICAL COMBINATION OF AN INSERT , A  DELETE AN UPDATE.

-- Use AIRLINESDB database
USE AIRLINESDB;

-- Comment: Displaying the contents of the 'FLIGHT_PASSENGER' table before the MERGE operation.
SELECT * FROM FLIGHT_PASSENGER;

-- Comment: Displaying the contents of the 'CHECK_IN' table before the MERGE operation.
SELECT * FROM CHECK_IN;

-- Comment: Merging data from the 'CHECK_IN' table into the 'FLIGHT_PASSENGER' table.
MERGE FLIGHT_PASSENGER AS F
USING CHECK_IN AS C
ON C.FIRSTNAME = F.FIRSTNAME
AND C.FLIGHTCODE = F.FLIGHTCODE
AND C.FLIGHTDATE = F.FLIGHTDATE

WHEN MATCHED 
	THEN UPDATE SET F.SEAT = C.SEAT

WHEN NOT MATCHED BY TARGET
	THEN INSERT (FIRSTNAME, FLIGHTCODE, FLIGHTDATE, SEAT)
	VALUES (C.FIRSTNAME, C.FLIGHTCODE, C.FLIGHTDATE, C.SEAT)

WHEN NOT MATCHED BY SOURCE 
	THEN DELETE;

-- Comment: Displaying the contents of the 'FLIGHT_PASSENGER' table after the MERGE operation.
SELECT * FROM FLIGHT_PASSENGER;
